// src/lib/auth.ts
// Server-only: mounted at /api/auth/* via src/routes/api/auth/$.tsx
import "dotenv/config";
import { betterAuth } from "better-auth";
import { Pool } from "pg";

export const auth = betterAuth({
	database: new Pool({
		connectionString: process.env.DATABASE_URL,
		ssl: { rejectUnauthorized: false }, // Required for Neon SSL termination
	}),
	emailAndPassword: {
		enabled: true,
	},
	// Google OAuth is wired but inert until GOOGLE_CLIENT_ID / SECRET exist in
	// .env — the conditional spread keeps dev booting without credentials.
	socialProviders: {
		...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
			? {
					google: {
						clientId: process.env.GOOGLE_CLIENT_ID,
						clientSecret: process.env.GOOGLE_CLIENT_SECRET,
					},
				}
			: {}),
	},
	advanced: {
		database: {
			// DB-side autoincrement ids (schema generated by better-auth CLI):
			// omit `id` on INSERT and let the Postgres sequence fill it.
			generateId: "serial",
		},
	},
});
