// src/lib/auth.ts
// Server-only: mounted at /api/auth/* via src/routes/api/auth/$.tsx
//
// DB ownership: this pg Pool OWNS the better-auth tables (user/session/
// account/verification). Prisma-next mirrors the same schema in
// src/prisma/schema.prisma purely as contract documentation — do not point
// two ORMs at writes for these tables.
//
// Admin plugin adds `role`/`banned`/`banReason`/`banExpires` columns to the
// user table (see schema.prisma). Promote an account with:
//   bun scripts/set-admin.ts someone@example.com
import "dotenv/config";
import { betterAuth } from "better-auth";
import { admin } from "better-auth/plugins";
import { Pool } from "pg";
import { resetPasswordEmail, sendMail, verificationEmail } from "@/lib/mail";

const appUrl = process.env.BETTER_AUTH_URL ?? "http://localhost:3000";
const appOrigin = (() => {
	try {
		return new URL(appUrl).origin;
	} catch {
		return "http://localhost:3000";
	}
})();

export const auth = betterAuth({
	database: new Pool({
		connectionString: process.env.DATABASE_URL,
		// Verified working with Neon's chain via system CAs. Override only if a
		// proxy/CA situation requires it by setting DATABASE_SSL_CA.
		ssl: process.env.DATABASE_SSL_CA
			? { ca: process.env.DATABASE_SSL_CA, rejectUnauthorized: true }
			: { rejectUnauthorized: true }, // Required for Neon SSL termination
	}),
	emailAndPassword: {
		enabled: true,
		// Sessions are only issued once emailVerified is true. Unverified
		// sign-in attempts fail with EMAIL_NOT_VERIFIED (handled in the UI).
		requireEmailVerification: true,
		sendResetPassword: async ({ user, url }) => {
			await sendMail({
				to: user.email,
				subject: "Reset your password | Unicorn Barber Training Academy",
				html: resetPasswordEmail(user.name ?? "", url),
			});
		},
	},
	emailVerification: {
		sendVerificationEmail: async ({ user, url }) => {
			// After better-auth verifies the token server-side it redirects to
			// callbackURL; route that to the dedicated success page.
			const target = new URL(url);
			target.searchParams.set(
				"callbackURL",
				new URL("/auth/verify-email?state=success", appOrigin).toString(),
			);
			await sendMail({
				to: user.email,
				subject: "Verify your email | Unicorn Barber Training Academy",
				html: verificationEmail(user.name ?? "", target.toString()),
			});
		},
		// Verification is mandatory (requireEmailVerification above): the mail
		// goes out on sign-up, and clicking the link auto-signs the user in.
		sendOnSignUp: true,
		autoSignInAfterVerification: true,
		expiresIn: 48 * 60 * 60,
	},
	rateLimit: {
		enabled: true,
		window: 60,
		max: 100,
		specialRules: [
			{ matcher: "/sign-in/email", window: 60, max: 10 },
			{ matcher: "/sign-up/email", window: 60, max: 5 },
			{ matcher: "/forget-password", window: 60, max: 3 },
			{ matcher: "/send-verification-email", window: 60, max: 3 },
			{ matcher: "/sign-in/social", window: 60, max: 20 },
		],
	},
	trustedOrigins: [appOrigin],
	// Google OAuth is wired but inert until GOOGLE_CLIENT_ID / SECRET exist in
	// .env — the conditional spread keeps dev booting without credentials.
	socialProviders: {
		...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
			? {
					google: {
						clientId: process.env.GOOGLE_CLIENT_ID,
						clientSecret: process.env.GOOGLE_CLIENT_SECRET,
					},
				}
			: {}),
	},
	plugins: [
		admin({
			defaultRole: "user",
			adminRoles: ["admin"],
		}),
	],
	advanced: {
		database: {
			// DB-side autoincrement ids (schema generated by better-auth CLI):
			// omit `id` on INSERT and let the Postgres sequence fill it.
			generateId: "serial",
		},
	},
});
